[general]
save_source_image = true
save_image_path = tmp_images
port = 7003

[monitoring]
metrics_prefix = jacktessery
grace_period = 900

[charge_level_pct]
enabled = true
json_path = charge_level_pct
max_value = 100
max_rate = 40

[input_power_w]
enabled = true
json_path = input.power_w
max_value = 800
max_rate = 800

[input_time_to_full_h]
enabled = true
json_path = input.time_to_full_h
max_value = 1000
max_rate = 1000

[output_power_w]
enabled = true
json_path = output.power_w
max_value = 2000
max_rate = 2000

[output_runtime_left_h]
enabled = true
json_path = output.runtime_left_h
max_value = 10000
max_rate = 10000

[solar_irradiance_wm2]
enabled = true
json_path = weather_check.solar_irradiance_wm2
max_value = 1500
max_rate = 1500

[cloud_cover_pct]
enabled = true
json_path = weather_check.cloud_cover_pct
max_value = 100
max_rate = 100

[is_day]
enabled = true
json_path = weather_check.is_day
max_value = 1
max_rate = 1

[daylight_hours]
enabled = true
json_path = sunrise_sunset.daylight_hours
max_value = 24
max_rate = 1

[hours_to_full]
enabled = true
json_path = charge_forecast.hours_to_full
max_value = 1000
max_rate = 1000

[days_needed]
enabled = true
json_path = charge_forecast.days_needed
max_value = 365
max_rate = 365
