[general]
save_source_image = true
save_image_path = tmp_images
port = 7003

[monitoring]
metrics_prefix = jacktessery
grace_period = 900

[charging_status]
enabled = true
max_value = 100
max_rate = 40
min_confidence = 60

[input_watts]
enabled = false
max_value = 800
max_rate = 800
min_confidence = 20

[output_watts]
enabled = false
max_value = 2000
max_rate = 2000
min_confidence = 60
